nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.9.2.cjs
compressionLevel: mixed  # Optimizes ZIP files in cache for git
enableGlobalCache: false  # Turns off the global cache, makes the use of local .yarn/cache